# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Friendships',
            field=models.ManyToManyField(related_name='_user_Friendships_+', to='myApp.User'),
        ),
    ]
